[manager]
sort_by = "natural"

[preview]
image_quality = 50
image_filter = "catmull-rom"

[open]
rules = [
    { mime = "text/*", use = [ "edit", "exec" ] },
    { mime = "image/*", use = [ "view-image" ] },
    { mime = "{audio,video}/*", use = [ "play" ] },
    { mime = "application/pdf", use = [ "view-pdf" ] },
    # Archives
    { mime = "application/{,g}zip", use = [ "extract", "thunar" ] },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "thunar" ] },
    # Folders
    { name = "*/", use = [ "thunar" ] },
    # Fallback
    { name = "*", use = [ "edit", "open", "exec", "thunar" ] },
]

[opener]
edit = [
    { run = 'nvim "$@"', desc = "Neovim", block = true, for = "unix" },
]
view-image = [
    { run = 'nsxiv "$@"', desc = "NSXIV", orphan = true, for = "unix" },
]
play = [
    { run = 'mpv --force-window "$@"', desc = "MPV", orphan = true, for = "unix" },
]
view-pdf = [
    { run = 'zathura "$@"', desc = "Zathura", orphan = true, for = "unix" },
]
extract = [
    { run = 'ya pub extract --list "$@"', desc = "Extract", for = "unix" },
]
thunar = [
    { run = 'thunar "$(realpath "$1")"', desc = "Show in Thunar", orphan = true, for = "linux" },
]
exec = [
    { run = '"$@"', desc = "Execute", for = "unix" },
]
open = [
    { run = 'xdg-open "$1"', desc = "XDG-Open", for = "linux" },
]
