#!/bin/bash
wmname LG3D

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x dunst >/dev/null || dunst &
pgrep -x pipewire >/dev/null || pipewire &
pgrep -x lxsession >/dev/null || lxsession &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x polybar >/dev/null || polybar main &
pgrep -x unclutter >/dev/null || unclutter -root &
pgrep -x mega-cmd-server >/dev/null || mega-cmd-server &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config window_gap 0
bspc config border_width 1
bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true

bspc config normal_border_color "#282828"
bspc config focused_border_color "#d8a657"
bspc config active_border_color "#282828"
bspc config presel_feedback_color "#d8a657"

bspc rule -a "Nitrogen" state=floating rectangle=900x500+10+10
bspc rule -a "KeePassXC" state=floating rectangle=900x500+1010+545
bspc rule -a "SpeedCrunch" state=floating rectangle=400x500+1510+10
bspc rule -a "Blueman-manager" state=floating rectangle=600x500+1310+545
