#!/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x dunst >/dev/null || dunst &
pgrep -x lxsession >/dev/null || lxsession &
pgrep -x polybar >/dev/null || polybar main &
pgrep -x unclutter >/dev/null || unclutter --root &

pgrep -x mega-cmd-server >/dev/null || mega-cmd-server &

nitrogen --restore

wmname LG3D

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config window_gap 0
bspc config border_width 1

bspc config split_ratio 0.5

bspc config single_monocle true
bspc config borderless_monocle true

bspc rule -a "Nitrogen" state=floating rectangle=900x500+10+10

# shellcheck ./theme
. ~/.config/bspwm/theme
