#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

pgrep -x dunst >/dev/null || dunst &
pgrep -x lxsession >/dev/null || lxsession &
pgrep -x megasync >/dev/null || megasync &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x polybar >/dev/null || polybar main &
pgrep -x udiskie >/dev/null || udiskie &
pgrep -x unclutter >/dev/null || unclutter --root &

nitrogen --restore

wmname LG3D

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config window_gap 0
bspc config border_width 1

bspc config split_ratio 0.5

bspc config single_monocle true
bspc config borderless_monocle true

# Start flavours
# Base16 Woodland
# by Jay Cornwall (https://jcornwall.com)
bspc config normal_border_color "#302b25"
bspc config focused_border_color "#d35c5c"
bspc config active_border_color "#9d8b70"
bspc config presel_feedback_color "#d35c5c"
# End flavours
