[[item]]
file = '~/.config/alacritty/theme.toml'
template = 'alacritty'
rewrite = true

[[item]]
file = '~/.config/bspwm/theme'
template = 'bspwm'
rewrite = true
hook = 'bspc wm -r'

[[item]]
file = '~/.config/dunst/dunstrc'
template = 'dunst'
rewrite = true
hook = 'killall dunst'

[[item]]
file = '~/.config/nvim/lua/misc/palette.lua'
template = 'nvim'
rewrite = true

[[item]]
file = '~/.config/polybar/colors.ini'
template = 'polybar'
rewrite = true
hook = 'polybar-msg cmd restart'

[[item]]
file = '~/.config/rofi/theme.rasi'
template = 'rofi'
rewrite = true

[[item]]
file = '~/.Xresources'
template = 'xresources'
rewrite = true
hook = 'xrdb ~/.Xresources'

[[item]]
file = '~/.config/zathura/theme.conf'
template = 'zathura'
rewrite = true

[[items]]
file = "~/.config/zellij/themes/default.kdl"
template = "zellij"
rewrite = true
