[[item]]
template = 'alacritty'
subtemplate = 'default'
file = '~/.config/alacritty/theme.toml'
rewrite = true

[[item]]
template = 'bspwm'
subtemplate = 'default'
file = '~/.config/bspwm/theme'
hook = 'bspc wm -r'
rewrite = true

[[item]]
template = 'dunst'
subtemplate = 'default'
file = '~/.config/dunst/dunstrc'
hook = 'killall dunst'
rewrite = true

[[item]]
template = 'nvim'
subtemplate = 'default'
file = '~/.config/nvim/lua/misc/palette.lua'
rewrite = true

[[item]]
template = 'polybar'
subtemplate = 'default'
file = '~/.config/polybar/colors.ini'
hook = 'polybar-msg cmd restart'
rewrite = true

[[item]]
template = 'rofi'
subtemplate = 'default'
file = '~/.config/rofi/theme.rasi'
rewrite = true

[[item]]
template = 'xresources'
subtemplate = 'default-256'
file = '~/.Xresources'
hook = 'xrdb ~/.Xresources'
rewrite = true

[[item]]
template = 'zathura'
subtemplate = 'default'
file = '~/.config/zathura/theme.conf'
rewrite = true

[[items]]
template = "zellij"
subtemplate = "default"
file = "~/.config/zellij/themes/default.kdl"
rewrite = true
