return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        highlight = { enable = true },
        indent = { enable = true, disable = { "dart" } },
        ensure_installed = {
          "arduino",
          "bash",
          "c",
          "c_sharp",
          "clojure",
          "cmake",
          "commonlisp",
          "cpp",
          "dart",
          "diff",
          "dockerfile",
          "elixir",
          "elm",
          "erlang",
          "fish",
          "git_config",
          "gitignore",
          "glsl",
          "go",
          "graphql",
          "html",
          "ini",
          "java",
          "javascript",
          "jsdoc",
          "json",
          "json5",
          "kotlin",
          "latex",
          "lua",
          "luadoc",
          "make",
          "ocaml",
          "perl",
          "php",
          "phpdoc",
          "prisma",
          "python",
          "regex",
          "ron",
          "ruby",
          "rust",
          "scss",
          "solidity",
          "sql",
          "svelte",
          "swift",
          "toml",
          "tsx",
          "typescript",
          "v",
          "vim",
          "vimdoc",
          "vue",
          "yaml",
          "yuck",
          "zig",
        },
        context_commentstring = {
          enable = true,
        },
      })
    end,
  },
}
