[[item]]
template = 'bspwm'
subtemplate = 'default'
file = '~/.config/bspwm/bspwmrc'
hook = 'bspc wm -r'

[[item]]
template = 'dunst'
subtemplate = 'default'
file = '~/.config/dunst/dunstrc'
hook = 'killall dunst'
rewrite = true

[[item]]
template = 'kitty'
subtemplate = 'default-256'
file = '~/.config/kitty/theme.conf'
hook = 'pkill -USR1 kitty'
rewrite = true

[[item]]
template = 'nvim'
subtemplate = 'default'
file = '~/.config/nvim/lua/plugins/mini-base16.lua'
rewrite = true

[[item]]
template = 'polybar'
subtemplate = 'default'
file = '~/.config/polybar/colors.ini'
hook = 'polybar-msg cmd restart'
rewrite = true

[[item]]
template = 'rofi'
subtemplate = 'default'
file = '~/.config/rofi/theme.rasi'
rewrite = true

[[item]]
template = 'xresources'
subtemplate = 'default-256'
file = '~/.Xresources'
hook = 'xrdb ~/.Xresources'
rewrite = true

[[item]]
template = 'zathura'
subtemplate = 'default'
file = '~/.config/zathura/theme.conf'
rewrite = true
